/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.31.1
 * source: Statistics.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum StatisticsPeriod {
    day = 0,
    week = 1,
    month = 2,
    year = 3,
    all = 4
}
export class StatisticsRequest extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        period?: StatisticsPeriod;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("period" in data && data.period != undefined) {
                this.period = data.period;
            }
        }
    }
    get period() {
        return pb_1.Message.getFieldWithDefault(this, 1, StatisticsPeriod.day) as StatisticsPeriod;
    }
    set period(value: StatisticsPeriod) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data: {
        period?: StatisticsPeriod;
    }): StatisticsRequest {
        const message = new StatisticsRequest({});
        if (data.period != null) {
            message.period = data.period;
        }
        return message;
    }
    toObject() {
        const data: {
            period?: StatisticsPeriod;
        } = {};
        if (this.period != null) {
            data.period = this.period;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.period != StatisticsPeriod.day)
            writer.writeEnum(1, this.period);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StatisticsRequest {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new StatisticsRequest();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.period = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): StatisticsRequest {
        return StatisticsRequest.deserialize(bytes);
    }
}
export class BlockerStatistics extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        total?: number;
        privacy?: number;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("total" in data && data.total != undefined) {
                this.total = data.total;
            }
            if ("privacy" in data && data.privacy != undefined) {
                this.privacy = data.privacy;
            }
        }
    }
    get total() {
        return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
    }
    set total(value: number) {
        pb_1.Message.setField(this, 1, value);
    }
    get privacy() {
        return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
    }
    set privacy(value: number) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        total?: number;
        privacy?: number;
    }): BlockerStatistics {
        const message = new BlockerStatistics({});
        if (data.total != null) {
            message.total = data.total;
        }
        if (data.privacy != null) {
            message.privacy = data.privacy;
        }
        return message;
    }
    toObject() {
        const data: {
            total?: number;
            privacy?: number;
        } = {};
        if (this.total != null) {
            data.total = this.total;
        }
        if (this.privacy != null) {
            data.privacy = this.privacy;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.total != 0)
            writer.writeInt64(1, this.total);
        if (this.privacy != 0)
            writer.writeInt64(2, this.privacy);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BlockerStatistics {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BlockerStatistics();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.total = reader.readInt64();
                    break;
                case 2:
                    message.privacy = reader.readInt64();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): BlockerStatistics {
        return BlockerStatistics.deserialize(bytes);
    }
}
export class StatisticsResponse extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(data?: any[] | {
        statistics?: BlockerStatistics;
        period?: StatisticsPeriod;
    }) {
        super();
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
        if (!Array.isArray(data) && typeof data == "object") {
            if ("statistics" in data && data.statistics != undefined) {
                this.statistics = data.statistics;
            }
            if ("period" in data && data.period != undefined) {
                this.period = data.period;
            }
        }
    }
    get statistics() {
        return pb_1.Message.getWrapperField(this, BlockerStatistics, 1) as BlockerStatistics;
    }
    set statistics(value: BlockerStatistics) {
        pb_1.Message.setWrapperField(this, 1, value);
    }
    get has_statistics() {
        return pb_1.Message.getField(this, 1) != null;
    }
    get period() {
        return pb_1.Message.getFieldWithDefault(this, 2, StatisticsPeriod.day) as StatisticsPeriod;
    }
    set period(value: StatisticsPeriod) {
        pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {
        statistics?: ReturnType<typeof BlockerStatistics.prototype.toObject>;
        period?: StatisticsPeriod;
    }): StatisticsResponse {
        const message = new StatisticsResponse({});
        if (data.statistics != null) {
            message.statistics = BlockerStatistics.fromObject(data.statistics);
        }
        if (data.period != null) {
            message.period = data.period;
        }
        return message;
    }
    toObject() {
        const data: {
            statistics?: ReturnType<typeof BlockerStatistics.prototype.toObject>;
            period?: StatisticsPeriod;
        } = {};
        if (this.statistics != null) {
            data.statistics = this.statistics.toObject();
        }
        if (this.period != null) {
            data.period = this.period;
        }
        return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.has_statistics)
            writer.writeMessage(1, this.statistics, () => this.statistics.serialize(writer));
        if (this.period != StatisticsPeriod.day)
            writer.writeEnum(2, this.period);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StatisticsResponse {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new StatisticsResponse();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    reader.readMessage(message.statistics, () => message.statistics = BlockerStatistics.deserialize(reader));
                    break;
                case 2:
                    message.period = reader.readEnum();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary(): Uint8Array {
        return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): StatisticsResponse {
        return StatisticsResponse.deserialize(bytes);
    }
}
